# Generated by Django 4.1.7 on 2023-04-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messengers', '0005_info_delete_newuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='bio',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='about',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
