# Generated by Django 4.1.7 on 2023-04-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messengers', '0007_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='sent_status',
            field=models.BooleanField(default=False),
        ),
    ]
