# Generated by Django 4.1.7 on 2023-04-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messengers', '0009_friends_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
