# Generated by Django 4.1.7 on 2023-07-19 00:27

import django.core.validators
from django.db import migrations, models
import messengers.models


class Migration(migrations.Migration):

    dependencies = [
        ('messengers', '0012_friends_friend_date_info_prof_pics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=messengers.models.user_directory_media, validators=[django.core.validators.FileExtensionValidator(['gif', 'png', 'jpeg', 'jpg', 'webp', 'avif', 'apng', 'mp4', 'webm', 'ogv', 'pdf', 'txt', 'csv', 'json', 'mp3', 'wav', 'oga'], 'Unsupported File format'), messengers.models.file_size_val, messengers.models.file_type_validator]),
        ),
    ]
