# Generated by Django 4.1.7 on 2023-07-21 21:02

import django.core.validators
from django.db import migrations, models
import messengers.models


class Migration(migrations.Migration):

    dependencies = [
        ('messengers', '0013_messages_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='prof_pics',
            field=models.ImageField(blank=True, null=True, upload_to=messengers.models.user_directory_path, validators=[django.core.validators.validate_image_file_extension, messengers.models.image_type_validator, messengers.models.file_size_val, django.core.validators.FileExtensionValidator(['gif', 'png', 'jpeg', 'jpg', 'webp', 'avif', 'apng'], 'Unsupported file format. Try a valid image format')]),
        ),
    ]
