# Generated by Django 4.1.7 on 2023-07-30 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messengers', '0017_group_membership_group_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='user',
            new_name='member',
        ),
        migrations.AlterField(
            model_name='group',
            name='admins',
            field=models.ManyToManyField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), related_name='admins', to=settings.AUTH_USER_MODEL),
        ),
    ]
