# Generated by Django 4.1.7 on 2023-07-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messengers', '0019_alter_group_admins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
