# Generated by Django 4.1.7 on 2023-07-30 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messengers', '0020_alter_messages_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='date_added',
            new_name='date_sent',
        ),
    ]
