# Generated by Django 4.1.7 on 2023-07-30 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messengers', '0022_groupmessages_alter_group_prof_pics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupMessages',
        ),
    ]
