# Generated by Django 4.1.7 on 2023-07-30 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messengers', '0025_alter_messages_receiver_delete_groupmessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='grp_receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grp_receiver', to='messengers.group'),
        ),
    ]
