# Generated by Django 4.1.7 on 2023-07-31 13:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messengers', '0028_messages_read_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='read_by',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
