# Generated by Django 4.1.8 on 2023-08-16 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messengers', '0029_alter_messages_read_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='notifications',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('group', 'member'), name='unique_membership'),
        ),
    ]
