# Generated by Django 4.1.8 on 2023-08-16 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messengers', '0030_info_notifications_membership_unique_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
