# Generated by Django 4.1.8 on 2023-08-27 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0001_initial'),
        ('messengers', '0031_friends_rejected'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='membership',
        #     name='group',
        # ),
        migrations.RemoveField(
            model_name='membership',
            name='inviter',
        ),
        # migrations.RemoveField(
        #     model_name='membership',
        #     name='member',
        # ),
        migrations.AlterField(
            model_name='messages',
            name='grp_receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='grp_receiver', to='Groups.group'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
