# Generated by Django 4.1.8 on 2023-08-31 20:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import messengers.validators
import messengers.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messengers', '0032_remove_membership_group_remove_membership_inviter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=messengers.models.user_directory_media, validators=[django.core.validators.FileExtensionValidator(
                ['gif', 'png', 'jpeg', 'jpg', 'webp', 'avif', 'apng', 'mp4', 'webm', 'ogv', 'pdf', 'txt', 'csv', 'json', 'mp3', 'wav', 'oga'], 'Unsupported File format', code='Invalid format'), messengers.validators.media_size_val, messengers.validators.file_type_validator]),
        ),
        migrations.AlterField(
            model_name='messages',
            name='read_by',
            field=models.ManyToManyField(
                blank=True, related_name='read_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
