# Generated by Django 4.1.8 on 2023-09-18 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messengers', '0033_alter_messages_media_alter_messages_read_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='prof_pics',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='media',
        ),
    ]
