# Generated by Django 4.1.8 on 2024-04-19 13:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('messengers', '0036_alter_messages_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
