# Generated by Django 4.1.8 on 2024-08-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messengers', '0037_friends_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='dark_theme',
            field=models.BooleanField(default=True),
        ),
    ]
