# Generated by Django 4.1.8 on 2024-08-12 14:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('messengers', '0039_alter_info_dark_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
