# Generated by Django 4.1.8 on 2024-08-12 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messengers', '0040_info_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='info',
            name='uuid',
        ),
    ]
