# Generated by Django 4.1.8 on 2024-08-12 15:29

from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    Model1 = apps.get_model('messengers', 'friends')
    Model2 = apps.get_model('messengers', 'info')
    for row in Model1.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])
    for row in Model2.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])


class Migration(migrations.Migration):
    dependencies = [
        ('messengers', '0042_friends_uuid_info_uuid'),
]
    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
]