# Generated by Django 4.1.8 on 2024-08-12 16:38

from django.db import migrations,models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('messengers', '0043_auto_20240812_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
