# Generated by Django 4.1.8 on 2023-09-18 14:50

import Groups.models
import django.core.validators
from django.db import migrations, models
import messengers.validators


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0002_remove_group_prof_pics'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='prof_pics',
            field=models.ImageField(blank=True, null=True, upload_to=Groups.models.group_directory_path, validators=[django.core.validators.validate_image_file_extension, messengers.validators.image_type_validator, messengers.validators.file_size_val, django.core.validators.FileExtensionValidator(['gif', 'png', 'jpeg', 'jpg', 'webp', 'avif', 'apng'], 'Unsupported file format. Try a valid image format')]),
        ),
    ]
