# Generated by Django 4.1.8 on 2024-04-23 16:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0003_group_prof_pics'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
