# Generated by Django 4.1.8 on 2024-08-12 14:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0004_membership_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
