# Generated by Django 4.1.8 on 2024-08-12 15:29

from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    Model1 = apps.get_model('Groups', 'Membership')
    Model2 = apps.get_model('Groups', 'Group')
    for row in Model1.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])
    for row in Model2.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])


class Migration(migrations.Migration):
    dependencies = [
        ('Groups', '0007_group_uuid_membership_uuid'),
]
    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
]
