# Generated by Django 4.1.8 on 2024-08-12 15:29

from django.db import migrations,models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0008_auto_20240812_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
